version: "3.6"

services:
  web:
    build:
      context: "."
      args:
        - NODE_ENV=development
    command: yarn start
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"

volumes:
  node_modules: {}
